[project]
name = "track2-day21-2a202601053-trancongchien"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dvc-s3>=3.3.0",
    "dvc[gs]==3.50.1",
    "fastapi==0.111.0",
    "google-cloud-storage==2.16.0",
    "joblib==1.4.2",
    "mlflow==2.13.0",
    "pandas==2.2.2",
    "pathspec==0.11.2",
    "pytest==8.2.0",
    "pyyaml==6.0.1",
    "scikit-learn==1.4.2",
    "uvicorn==0.29.0",
]
